version: "3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks: 
      - default
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    networks:
      - default

  directus:
    image: wafflehacks/cms:dev
    build: .
    ports:
      - 8080:8055
    networks:
      - default
    depends_on: 
      - postgres
      - redis
    volumes:
      - ./.docker/directus:/directus/uploads
    env_file: ./dev.env
    environment: 
      KEY: "development-key"
      SECRET: "development-secret"
      PUBLIC_URL: "http://127.0.0.1:8080"

      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://redis:6379"

      ADMIN_EMAIL: "admin@user.com"
      ADMIN_PASSWORD: "admin"

      OAUTH_PROVIDERS: "discord"
      OAUTH_DISCORD_SCOPE: "identify email guilds"


networks:
  default:
