name = "auto-build"
type = "javascript"

account_id = "200a2fa0d0fd6259eba3ff410b2936e8"
workers_dev = true

compatibility_date = "2021-11-03"

[vars]
ACCOUNT_ID = "200a2fa0d0fd6259eba3ff410b2936e8"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
